name: Week 6 Run Apex Unit Tests Manually

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install sfdx with npm
              run: |
                  npm i @salesforce/cli --global

            - name: Scan code
              run: |
                sf scanner run --format sarif --target '/force-app' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v3
              with:
                  # Path to SARIF file relative to the root of the repository
                  sarif_file: apexScanResults.sarif
